name: External Trigger Main

on:
  workflow_dispatch:

jobs:
  external-trigger-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: External Trigger
        if: github.ref == 'refs/heads/development'
        run: |
          if [ -n "${{ secrets.PAUSE_EXTERNAL_TRIGGER_OMBI_DEVELOPMENT }}" ]; then
            echo "Github secret PAUSE_EXTERNAL_TRIGGER_OMBI_DEVELOPMENT is set; skipping trigger."
            exit 0
          fi
          echo "External trigger running off of development branch. To disable this trigger, set a Github secret named \"PAUSE_EXTERNAL_TRIGGER_OMBI_DEVELOPMENT\"."
          echo "Setting env vars"
          CONTAINER_NAME='ombi'
          BUILD_VERSION_ARG='OMBI_RELEASE'
          LS_USER='linuxserver'
          LS_REPO='docker-ombi'
          DOCKERHUB_IMAGE='linuxserver/ombi'
          DEV_DOCKERHUB_IMAGE='lsiodev/ombi'
          PR_DOCKERHUB_IMAGE='lspipepr/ombi'
          DIST_IMAGE='ubuntu'
          DIST_TAG='bionic'
          MULTIARCH='true'
          CI='true'
          CI_WEB='true'
          CI_PORT='3579'
          CI_SSL='false'
          CI_DELAY='120'
          CI_DOCKERENV='TZ=US/Pacific'
          CI_AUTH='user:password'
          CI_WEBPATH=''
          echo "Retrieving external version"
          EXT_RELEASE=$(curl -sL GET https://ci.appveyor.com/api/projects/tidusjar/requestplex/history?recordsNumber=100 | jq -r '. | first(.builds[] | select(.status == "success") | select(.branch == "develop") | select(.pullRequestId == null)) | .version')
          if [ -z "${EXT_RELEASE}" ]; then
            echo "Can't retrieve external version, exiting"
            FAILURE_REASON="Can't retrieve external version for ombi branch development"
            curl -X POST -H "Content-Type: application/json" --data '{"avatar_url": "https://cdn.discordapp.com/avatars/354986384542662657/df91181b3f1cf0ef1592fbe18e0962d7.png","embeds": [{"color": 16711680,
              "description": "**Trigger Failed** \n**Reason:** '"${FAILURE_REASON}"' \n"}],
              "username": "Github Actions"}' ${{ secrets.DISCORD_WEBHOOK }}
            exit 1
          fi
          echo "External version: ${EXT_RELEASE}"
          echo "Retrieving last pushed version"
          image="${LS_USER}/ombi"
          tag="development"
          token=$(curl -s \
            "https://auth.docker.io/token?scope=repository:${image}:pull&service=registry.docker.io" \
            | jq -r '.token')
          digest=$(curl -s \
            --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            --header "Authorization: Bearer ${token}" \
            "https://registry-1.docker.io/v2/${image}/manifests/${tag}" \
            | jq -r '.config.digest')
          image_info=$(curl -sL \
            --header "Authorization: Bearer ${token}" \
            "https://registry-1.docker.io/v2/${image}/blobs/${digest}" \
            | jq -r '.container_config')
          IMAGE_RELEASE=$(echo ${image_info} | jq -r '.Labels.build_version' | awk '{print $3}')
          IMAGE_VERSION=$(echo ${IMAGE_RELEASE} | awk -F'-ls' '{print $1}')
          if [ -z "${IMAGE_VERSION}" ]; then
            echo "Can't retrieve last pushed version, exiting"
            FAILURE_REASON="Can't retrieve last pushed version for ombi tag development"
            curl -X POST -H "Content-Type: application/json" --data '{"avatar_url": "https://cdn.discordapp.com/avatars/354986384542662657/df91181b3f1cf0ef1592fbe18e0962d7.png","embeds": [{"color": 16711680,
              "description": "**Trigger Failed** \n**Reason:** '"${FAILURE_REASON}"' \n"}],
              "username": "Github Actions"}' ${{ secrets.DISCORD_WEBHOOK }}
            exit 1
          fi
          echo "Last pushed version: ${IMAGE_VERSION}"
          if [ "${EXT_RELEASE}" == "${IMAGE_VERSION}" ]; then
            echo "Version ${EXT_RELEASE} already pushed, exiting"
            exit 0
          else
            echo "New version ${EXT_RELEASE} found; old version was ${IMAGE_VERSION}. Triggering new build"
            curl -X POST \
              https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-ombi/job/development/buildWithParameters?PACKAGE_CHECK=false \
              --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}
            echo "Notifying Discord"
            TRIGGER_REASON="A version change was detected for ombi tag development. Old version:${IMAGE_VERSION} New version:${EXT_RELEASE}"
            curl -X POST -H "Content-Type: application/json" --data '{"avatar_url": "https://cdn.discordapp.com/avatars/354986384542662657/df91181b3f1cf0ef1592fbe18e0962d7.png","embeds": [{"color": 9802903,
              "description": "**Build Triggered** \n**Reason:** '"${TRIGGER_REASON}"' \n"}],
              "username": "Github Actions"}' ${{ secrets.DISCORD_WEBHOOK }}
          fi
